### ISSUE TITLE
No metadata for "PackagingModule" was found.

### ISSUE THREAD

**Issue by laibarif** [KhadimHussainDev/TheExportersLoom-Apis#22] opened 2024-11-26 07:15 UTC
[Nest] 13500  - 11/26/2024, 12:13:25 PM   ERROR [ExceptionsHandler] No metadata for "PackagingModule" was found.
EntityMetadataNotFoundError: No metadata for "PackagingModule" was found.
    at DataSource.getMetadata (F:\SEMESTER DATA\FYP\Backend\TheExportersLoom-Apis\node_modules\typeorm\data-source\src\data-source\DataSource.ts:450:30)
    at Repository.get metadata (F:\SEMESTER DATA\FYP\Backend\TheExportersLoom-Apis\node_modules\typeorm\repository\src\repository\Repository.ts:53:40)
    at Repository.create (F:\SEMESTER DATA\FYP\Backend\TheExportersLoom-Apis\node_modules\typeorm\repository\src\repository\Repository.ts:130:18)
    at PackagingService.createPackagingModule (F:\SEMESTER DATA\FYP\Backend\TheExportersLoom-Apis\src\modules\packaging module\packaging.service.ts:49:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    
    at <anonymous> (F:\SEMESTER DATA\FYP\Backend\TheExportersLoom-Apis\src\project\project.service.ts:111:7)
    at EntityManager.transaction (F:\SEMESTER DATA\FYP\Backend\TheExportersLoom-Apis\node_modules\typeorm\entity-manager\src\entity-manager\EntityManager.ts:154:28)      
    at ProjectService.createProject (F:\SEMESTER DATA\FYP\Backend\TheExportersLoom-Apis\src\project\project.service.ts:31:12)
    at ProjectController.createProject (F:\SEMESTER DATA\FYP\Backend\TheExportersLoom-Apis\src\project\project.controller.ts:13:12)
    at async F:\SEMESTER DATA\FYP\Backend\TheExportersLoom-Apis\node_modules\@nestjs\core\router\router-execution-context.js:46:28 
![Screenshot 2024-11-26 121522](https://github.com/user-attachments/assets/caddabe4-afc1-4420-93b7-3f265b4e890b)

**Comment by MuqaddasNazeer** [comment] 2024-11-27 15:00
**Issue:**
The main issue was a mismatch in naming between the entity and the module in the NestJS application. The entity was mistakenly named PackagingModule, while the corresponding module was named Packaging. As a result, TypeORM was unable to recognize the entity, leading to errors related to metadata not being found.

**Root Cause:**
The issue stemmed from the following:

The entity was named PackagingModule, which conflicted with the name of the module (Packaging).
Due to this naming inconsistency, the Packaging module was imported in place of the PackagingModule entity, causing TypeORM to fail in identifying the correct entity metadata.
Solution:
**To resolve this, we:**

Renamed the Entity: Changed the entity name from PackagingModule to Packaging to align with the module naming convention
![image](https://github.com/user-attachments/assets/c7f2963f-28da-454b-ac9f-1f9577262a68)
Updated the Imports: Ensured that the Packaging entity was correctly imported into the module, replacing any references to the incorrectly named PackagingModule.
![image](https://github.com/user-attachments/assets/741f0323-612d-4c9e-b70f-6b091281f988)
Verified Entity Registration: Confirmed that the Packaging entity was properly registered in the module and TypeORM configuration. also made changes in other packging module files 
**Outcome:**
After making these changes, the entity was properly recognized by TypeORM, resolving the metadata error. The Packaging module now functions as expected, with the entity correctly linked to the database.

**Closed by MuqaddasNazeer** 2024-11-27 15:00 UTC
Labels: bug
